name: Get Deals for electronics

on:
  push:
    branches:
      - master
  schedule:
  - cron: "0 * * * *"

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Python script
      run: |
        python fetch_deals.py