name: Get Deals for electronics

on:
  repository_dispatch:
    types: fetch-deals
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Python script
      run: |
        python fetch_deals.py

    - name: setup git config
      run: |
        git config user.name "GitHub Commit Bot"
        git config user.email "bot@doAction.com"

    - name: commit
      run: |
        git add deals.md
        git commit -m "Updated Readme using Bot"
        git push origin master